name: quizzy
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^0.13.0
  panara_dialogs: ^0.1.4
  breadcrumbs: ^0.1.0
  quickalert: ^1.0.1
  flutter_custom_buttons: ^0.0.3
  carousel_slider: ^4.0.0
  intl: ^0.17.0
  shimmer: ^2.0.0
  image_picker: ^0.8.4+4
  fluttertoast: ^8.2.2
  shared_preferences: ^2.0.8
  google_mobile_ads: ^3.0.0
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  overlay_support: ^2.1.0
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^5.0.11
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatar.png
    - assets/images/logo.png
