// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnr9R4J1ywfp-bdt4F_Nh1hlvaeQPTlI8',
    appId: '1:733623030521:android:a1d76105c38d6ed2aec828',
    messagingSenderId: '733623030521',
    projectId: 'quizzy-4a9ce',
    storageBucket: 'quizzy-4a9ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs0fYjdNL4-f_3dg4UCwBejkvPG90qcTo',
    appId: '1:733623030521:ios:daa25a498da23b8eaec828',
    messagingSenderId: '733623030521',
    projectId: 'quizzy-4a9ce',
    storageBucket: 'quizzy-4a9ce.appspot.com',
    androidClientId: '733623030521-3ni75foff703r57jj5r6k27cne3fc9er.apps.googleusercontent.com',
    iosClientId: '733623030521-0gefiutja9tmk8u0vmnbnlf2a1733i44.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzy',
  );
}
